//! Phase 13: cross-module RSF-native invariant suite — ACCEL-BACKED SPEC.
//!
//! These are the invariants whose import closure reaches
//! `src/processor/rsf.zig`, and through it
//! `src/hw/accel/accel_interface.zig`. That module declares the Futhark C
//! entry points as `pub extern "c"` and calls them from its destructors, so an
//! artifact that reaches it cannot link until the gitignored
//! `src/hw/accel/main_cpu.c` has been generated by `zig build regen-futhark`.
//!
//! Registered as `test-rsf-native-accel`. Without the `futhark` binary this
//! spec is BLOCKED at link time; it is never reported as passing.

const std = @import("std");
const jaide = @import("jaide");
const rsf_mod = jaide.rsf;
const types = jaide.types;

const RSF = rsf_mod.RSF;

// ---------------------------------------------------------------------------
// Deterministic PRNG (splitmix64), identical to the accel-free spec's.
// ---------------------------------------------------------------------------

const Rng = struct {
    state: u64,

    fn init(seed: u64) Rng {
        return .{ .state = seed };
    }

    fn nextU64(self: *Rng) u64 {
        self.state +%= 0x9E37_79B9_7F4A_7C15;
        var z = self.state;
        z = (z ^ (z >> 30)) *% 0xBF58_476D_1CE4_E5B9;
        z = (z ^ (z >> 27)) *% 0x94D0_49BB_1331_11EB;
        return z ^ (z >> 31);
    }

    fn nextF32(self: *Rng) f32 {
        const v = self.nextU64() >> 40;
        return @as(f32, @floatFromInt(v)) / 8388608.0 - 1.0;
    }
};

// ---------------------------------------------------------------------------
// R-GPU sharded execution: the sharded fabric must reproduce the model
// ---------------------------------------------------------------------------

const r_gpu = jaide.r_gpu;

fn makeTestModel(allocator: std.mem.Allocator, dim: usize, layers: usize, diffusion: bool) !RSF {
    // `model_dim` is the coupling width (half the latent row length); the
    // latent row is `2·dim` floats.
    var model = try RSF.initWithConfig(allocator, dim, layers, rsf_mod.RSFConfig{ .global_diffusion = diffusion });
    // Deterministic, spectrally-bounded couplings so the comparison is
    // reproducible and the stack stays well conditioned.
    var rng = Rng.init(0x0DE0_0000 +% @as(u64, dim));
    const s_buf = try allocator.alloc(f32, dim * 2);
    defer allocator.free(s_buf);
    const t_buf = try allocator.alloc(f32, dim * 2);
    defer allocator.free(t_buf);
    var l: usize = 0;
    while (l < layers) : (l += 1) {
        for (0..dim) |d| {
            s_buf[d * 2 + 0] = rng.nextF32() * 0.02;
            s_buf[d * 2 + 1] = rng.nextF32() * 0.05;
            t_buf[d * 2 + 0] = rng.nextF32() * 0.02;
            t_buf[d * 2 + 1] = rng.nextF32() * 0.05;
        }
        try model.writeLayerWeights(l, s_buf, t_buf);
    }
    return model;
}

fn fillLatent(state: *rsf_mod.RSFLatentState, dim: usize, batch: usize, seed: u64) !void {
    var rng = Rng.init(seed);
    for (0..batch) |b| {
        const even = try state.evenView();
        const odd = try state.oddView();
        for (0..dim) |d| {
            try even.set(b, d, rng.nextF32() * 0.4);
            try odd.set(b, d, rng.nextF32() * 0.4);
        }
    }
}

test "rsfNative_rgpuShardedEquivalence" {
    const allocator = std.testing.allocator;
    const dim: usize = 32;
    const layers: usize = 4;
    const batch: usize = 3;

    for ([_]bool{ false, true }) |diffusion| {
        var model = try makeTestModel(allocator, dim, layers, diffusion);
        defer model.deinit();
        try std.testing.expectEqual(diffusion, try model.globalDiffusionEnabled());

        var rgpu = try r_gpu.RelationalGraphProcessingUnit.init(allocator, 2, 2);
        defer rgpu.deinit();
        try rgpu.distributeRSFModel(&model);

        var reference = try rsf_mod.RSFLatentState.init(allocator, &model, batch);
        defer reference.deinit();
        var sharded = try rsf_mod.RSFLatentState.init(allocator, &model, batch);
        defer sharded.deinit();
        try fillLatent(&reference, dim, batch, 0x51DE_0000);
        try sharded.data.copyFrom(&reference.data);
        reference.log_det = 0.0;
        sharded.log_det = 0.0;

        const reference_logdet = try model.forwardLatentWithLogDet(&reference);
        try rgpu.forwardRSF(&model, &sharded);

        // Equivalence gate: abs 1e-4 + rel 1e-3 elementwise.
        for (reference.data.data, sharded.data.data) |a, b| {
            const tol = 1e-4 + 1e-3 * @abs(a);
            try std.testing.expect(@abs(a - b) <= tol);
        }
        try std.testing.expect(@abs(reference_logdet - sharded.log_det) < 1e-3);

        const stats = rgpu.getStatistics();
        if (diffusion) {
            try std.testing.expect(stats.diffusion_exchanges > 0);
        } else {
            try std.testing.expectEqual(@as(usize, 0), stats.diffusion_exchanges);
        }
        try std.testing.expect(stats.rsf_coupling_ops > 0);
        try std.testing.expectEqual(batch, stats.rsf_rows_flowed);
    }
}

test "rsfNative_rgpuRoundtripThroughShardedInverse" {
    const allocator = std.testing.allocator;
    const dim: usize = 16;
    const layers: usize = 3;
    const batch: usize = 2;

    var model = try makeTestModel(allocator, dim, layers, true);
    defer model.deinit();
    var rgpu = try r_gpu.RelationalGraphProcessingUnit.init(allocator, 2, 2);
    defer rgpu.deinit();
    try rgpu.distributeRSFModel(&model);

    var state = try rsf_mod.RSFLatentState.init(allocator, &model, batch);
    defer state.deinit();
    var original = try rsf_mod.RSFLatentState.init(allocator, &model, batch);
    defer original.deinit();
    try fillLatent(&state, dim, batch, 0x07F1_0001);
    try original.data.copyFrom(&state.data);
    state.log_det = 0.0;

    try rgpu.forwardRSF(&model, &state);
    try rgpu.inverseRSF(&model, &state);

    var num: f64 = 0.0;
    var den: f64 = 0.0;
    for (original.data.data, state.data.data) |a, b| {
        const diff: f64 = @as(f64, a) - @as(f64, b);
        num += diff * diff;
        den += @as(f64, a) * @as(f64, a);
    }
    const rel = @sqrt(num / @max(den, 1e-30));
    try std.testing.expect(rel < 1e-4);

    // The accumulated log-det returns to zero across a full round trip.
    try std.testing.expect(@abs(state.log_det) < 1e-3);
}

test "rsfNative_rgpuPartitionIsDiffusionAligned" {
    // The default production geometry: dim = 49152, block = 32768, stages = 15.
    // On 8 cores the rule picks c' = 6 (dim/6 = 8192 = 2^13 <= 16384), leaving
    // 2 cores idle and 2 crossing butterfly stages plus one Q_r round.
    const part = try r_gpu.planRSFPartition(49152, 8, true);
    try std.testing.expectEqual(@as(usize, 6), part.active_cores);
    try std.testing.expectEqual(@as(usize, 2), part.idle_cores);
    try std.testing.expectEqual(@as(usize, 8192), part.shard_len);
    try std.testing.expectEqual(@as(usize, 15), part.layout.stages);
    try std.testing.expect(part.shard_len <= part.layout.block / 2);
    try std.testing.expectEqual(@as(usize, 13), part.local_stages);
    try std.testing.expectEqual(@as(usize, 2), part.cross_stages);

    // Diffusion disabled: contiguous split, no exchanges at all.
    const plain = try r_gpu.planRSFPartition(32, 4, false);
    try std.testing.expectEqual(@as(usize, 8), plain.shard_len);
    try std.testing.expectEqual(@as(usize, 4), plain.active_cores);
    try std.testing.expectEqual(@as(usize, 0), plain.exchange_rounds_per_layer);

    // A single core performs the whole diffusion locally.
    const solo = try r_gpu.planRSFPartition(32, 1, true);
    try std.testing.expectEqual(@as(usize, 1), solo.active_cores);
    try std.testing.expectEqual(@as(usize, 0), solo.cross_stages);

    // Both intervals of a coupling index live on the same core.
    const p = try r_gpu.planRSFPartition(16, 2, true);
    for (0..16) |d| {
        try std.testing.expectEqual(p.coreOf(d), p.coreOfRowIndex(16, d));
        try std.testing.expectEqual(p.coreOf(d), p.coreOfRowIndex(16, 16 + d));
    }
}

// ---------------------------------------------------------------------------
// Gate 9(a): midpoint frontier depth accounting
// ---------------------------------------------------------------------------

test "rsfNative_midpointDepthAccounting" {
    const allocator = std.testing.allocator;
    const layers: usize = 8;
    const dim: usize = 12;
    const batch: usize = 2;

    var model = try makeTestModel(allocator, dim, layers, true);
    defer model.deinit();

    const split = try model.midpointSplit();
    try std.testing.expectEqual(layers, split.forward_layers + split.backward_layers);
    try std.testing.expectEqual(layers / 2, split.forward_layers);
    // Each frontier traverses at most ceil(L/2) layers.
    const half = (layers + 1) / 2;
    try std.testing.expect(split.forward_layers <= half);
    try std.testing.expect(split.backward_layers <= half);

    var input = try rsf_mod.RSFLatentState.init(allocator, &model, batch);
    defer input.deinit();
    try fillLatent(&input, dim, batch, 0x01D0_0001);

    // y* = F(x0): because F ∈ Aut(AD) the collision is exact.
    var target = try input.clone(allocator);
    defer target.deinit();
    _ = try model.forwardLatentWithLogDet(&target);

    model.resetLayerApplicationCounter();
    var result = try model.midpointCollision(&input, &target, allocator);
    defer result.deinit();

    try std.testing.expectEqual(split.forward_layers, result.forward_layers);
    try std.testing.expectEqual(split.backward_layers, result.backward_layers);
    // Exact automorphism ⇒ exact collision.
    try std.testing.expect(result.collision_loss < 1e-6);
    // Both frontiers accumulate +Σ clip, so the total is the log-det of F.
    try std.testing.expect(@abs(result.logdet_total - (result.logdet_forward + result.logdet_backward)) < 1e-6);
    try std.testing.expectEqual(layers, model.layerApplicationCount());
    try std.testing.expect(model.lastFrontierDepth() <= half);

    // The sequential and concurrent traversals agree.
    model.resetLayerApplicationCounter();
    var parallel = try model.midpointCollisionParallel(&input, &target, allocator);
    defer parallel.deinit();
    try std.testing.expect(@abs(parallel.collision_loss - result.collision_loss) < 1e-6);
    try std.testing.expect(@abs(parallel.logdet_total - result.logdet_total) < 1e-4);
    try std.testing.expectEqual(layers, model.layerApplicationCount());
}
